### ISSUE TITLE
chat formatting

### ISSUE THREAD

**Issue by SN0WM0DE** [PokemonGO-REMOTE-RAIDERS/moderator-documentation#21]
@nickhempsey in the chat formatting section... Add coding for what u have in #fast_clickers

**Comment by nickhempsey** [comment]
## How to insert code snippets and blocks.

Code snippets and Code blocks both use backticks on either end of a string of code or content.  This is a backtick `. 

- **Code snippets** use one backtick and are inline elements that will sit next to the text `like this`.
- **Code blocks** use three backticks and will fall to a new line
``like this``
 
### iPhone

To use the backtick on iPhone you long tap, this is not a press it's more like when you want to move apps on your homescreen.  You long tap the single quote and select the backtick (the furthest to the left).

![backtick-iphone](https://user-images.githubusercontent.com/573588/109347586-61908280-7841-11eb-86f3-e5ae04bf68b7.png)

### Android

To use a backtick on an Android you must go to page 2 of 2 in the specials characters keyboard. 

![backtick-android](https://user-images.githubusercontent.com/573588/109347684-897fe600-7841-11eb-9eef-cdcd2caefdc9.png)

### Desktop

To use a backtick on a desktop keyboard simply click the backtick, it's at the top left of the keyboard, below the ESC, and above the TAB. 

![backtick-desktop](https://user-images.githubusercontent.com/573588/109347813-b8965780-7841-11eb-8dd9-995330d7c2af.png)

**Comment by nickhempsey** [comment]
@PokemonGO-REMOTE-RAIDERS/copywriters Can someone please proofread this for me?

Thank you!

**Comment by calummoore86** [comment]
Looks ok to me
