### ISSUE TITLE
Amendment to Roles and Responsibilities

### ISSUE THREAD

**Issue by calummoore86** [PokemonGO-REMOTE-RAIDERS/moderator-documentation#23]
This part of roles and responsibilities needs to be amended. MITs dont have manager role..

![Screenshot_20210226-203012_Chrome](https://user-images.githubusercontent.com/12052567/109352003-117de400-7872-11eb-9979-9bc2b5f6a5c0.jpg)

**Comment by nickhempsey** [comment]
@calummoore86 

MIT's don't have the manager role, but this is saying that a moderator should respond to the @canIspeak2manager tag if an MIT doesn't get to it first.  Meaning that they may happen upon it and take care of it.  I'm not sure how to best clarify it other than just deleting it. What are you thinking.  

@PokemonGO-REMOTE-RAIDERS/copywriters anything to add?

**Comment by calummoore86** [comment]
Im not sure exactly what to replace it with, but it seems to imply the MITs would be first repsonders to manager tag. It may just be badly worded. Could delete everything after the comma to avoid confusion.

**Comment by nickhempsey** [comment]
Let's go with removing it for now and we can circle back if someone comes up with better phrasing.
